name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v1

      - name: shellcheck
        uses: azohra/shell-linter@v0.2.0

      - name: hadolint
        uses: brpaz/hadolint-action@master

      - name: Build image
        run: ./build.sh

      - name: Run tests
        run: ./test/test.sh

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      - name: Log in to dockerhub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy image
        run: ./build.sh --push --latest
